using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SymphonyFrameWork.Generators
{
    /// <summary>
    ///     Roslyn Source GeneratorのUPM配布経路を検証するための最小Generator。
    /// </summary>
    [Generator]
    public sealed class PrototypeMarkerGenerator : IIncrementalGenerator
    {
        /// <summary> 検出する属性の完全修飾名。 </summary>
        private const string ATTRIBUTE_METADATA_NAME =
            "SymphonyFrameWork.Generators.Prototype.GeneratePrototypeMarkerAttribute";

        /// <summary> 生成するマーカー文字列。 </summary>
        private const string GENERATED_MARKER = "Symphony Roslyn Generator Active";

        /// <summary>
        ///     属性付きpartial classを収集して決定的なマーカープロパティを生成する。
        /// </summary>
        /// <param name="context"> Generatorの初期化コンテキスト。 </param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 本プロトタイプが扱えるトップレベルの非generic partial classだけを収集する。
            IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> targets = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ATTRIBUTE_METADATA_NAME,
                    static (node, _) => IsSupportedDeclaration(node),
                    static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol)
                .Where(static symbol => symbol.ContainingType == null && !symbol.IsGenericType)
                .Collect();

            // 同じ入力に対して同じhint nameとソース順になるよう、出力直前に整列する。
            context.RegisterSourceOutput(targets, static (productionContext, symbols) =>
                EmitTargets(productionContext, symbols));
        }

        /// <summary>
        ///     構文上、本プロトタイプが生成対象にできる宣言かを判定する。
        /// </summary>
        /// <param name="node"> 属性が付いた構文ノード。 </param>
        /// <returns> partial classの場合はtrue。 </returns>
        private static bool IsSupportedDeclaration(SyntaxNode node)
        {
            if (!(node is ClassDeclarationSyntax declaration)) { return false; }

            return declaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
        }

        /// <summary>
        ///     収集した対象へマーカープロパティを生成する。
        /// </summary>
        /// <param name="context"> ソース出力コンテキスト。 </param>
        /// <param name="symbols"> 生成対象の型シンボル。 </param>
        private static void EmitTargets(
            SourceProductionContext context,
            ImmutableArray<INamedTypeSymbol> symbols)
        {
            // partial宣言が複数あっても型ごとに1回だけ生成する。
            HashSet<string> generatedTypeNames = new(StringComparer.Ordinal);
            foreach (INamedTypeSymbol symbol in symbols
                         .OrderBy(
                             target => target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                             StringComparer.Ordinal))
            {
                string fullName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!generatedTypeNames.Add(fullName)) { continue; }

                string source = BuildSource(symbol);
                string hintName = BuildHintName(fullName);
                context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
            }
        }

        /// <summary>
        ///     対象型へ追加するpartial宣言を組み立てる。
        /// </summary>
        /// <param name="symbol"> 生成対象の型シンボル。 </param>
        /// <returns> 生成するC#ソース。 </returns>
        private static string BuildSource(INamedTypeSymbol symbol)
        {
            string namespaceName = symbol.ContainingNamespace.ToDisplayString();
            string typeName = EscapeIdentifier(symbol.Name);
            StringBuilder builder = new();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.Append("namespace ").Append(namespaceName).AppendLine();
            builder.AppendLine("{");
            builder.Append("    partial class ").Append(typeName).AppendLine();
            builder.AppendLine("    {");
            builder.Append("        internal static string SymphonyGeneratedMarker => \"")
                .Append(GENERATED_MARKER)
                .AppendLine("\";");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        /// <summary>
        ///     完全修飾型名からファイル名として安定したhint nameを作る。
        /// </summary>
        /// <param name="fullName"> 対象型の完全修飾名。 </param>
        /// <returns> Generator出力のhint name。 </returns>
        private static string BuildHintName(string fullName)
        {
            StringBuilder builder = new(fullName.Length + 16);
            foreach (char character in fullName)
            {
                builder.Append(char.IsLetterOrDigit(character) || character == '_'
                    ? character
                    : '_');
            }

            return builder.Append(".g.cs").ToString();
        }

        /// <summary>
        ///     C#キーワードと衝突する識別子をエスケープする。
        /// </summary>
        /// <param name="identifier"> 型名の識別子。 </param>
        /// <returns> ソースへ書き込める識別子。 </returns>
        private static string EscapeIdentifier(string identifier) =>
            SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None
                ? identifier
                : "@" + identifier;
    }
}
